// Code generated by protoc-gen-go. DO NOT EDIT.
// source: version.proto

package version_go_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A note that indicates the multiple versions from a resource
type Version struct {
	// Required. Image name
	ImageName            string      `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	Versions             []*Versions `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d2c07d79758f814, []int{0}
}

func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetImageName() string {
	if m != nil {
		return m.ImageName
	}
	return ""
}

func (m *Version) GetVersions() []*Versions {
	if m != nil {
		return m.Versions
	}
	return nil
}

// Details of a version
type Versions struct {
	// Required. Version number
	Tag string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	// Not required
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Versions) Reset()         { *m = Versions{} }
func (m *Versions) String() string { return proto.CompactTextString(m) }
func (*Versions) ProtoMessage()    {}
func (*Versions) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d2c07d79758f814, []int{1}
}

func (m *Versions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Versions.Unmarshal(m, b)
}
func (m *Versions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Versions.Marshal(b, m, deterministic)
}
func (m *Versions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Versions.Merge(m, src)
}
func (m *Versions) XXX_Size() int {
	return xxx_messageInfo_Versions.Size(m)
}
func (m *Versions) XXX_DiscardUnknown() {
	xxx_messageInfo_Versions.DiscardUnknown(m)
}

var xxx_messageInfo_Versions proto.InternalMessageInfo

func (m *Versions) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Versions) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Version)(nil), "grafeas.v1beta1.version.Version")
	proto.RegisterType((*Versions)(nil), "grafeas.v1beta1.version.Versions")
}

func init() { proto.RegisterFile("version.proto", fileDescriptor_7d2c07d79758f814) }

var fileDescriptor_7d2c07d79758f814 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4b, 0x2d, 0x2a,
	0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4f, 0x2f, 0x4a, 0x4c, 0x4b,
	0x4d, 0x2c, 0xd6, 0x2b, 0x33, 0x4c, 0x4a, 0x2d, 0x49, 0x34, 0xd4, 0x83, 0x4a, 0x2b, 0xa5, 0x73,
	0xb1, 0x87, 0x41, 0x98, 0x42, 0xb2, 0x5c, 0x5c, 0x99, 0xb9, 0x89, 0xe9, 0xa9, 0xf1, 0x79, 0x89,
	0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x9c, 0x60, 0x11, 0xbf, 0xc4, 0xdc, 0x54,
	0x21, 0x5b, 0x2e, 0x0e, 0xa8, 0xa6, 0x62, 0x09, 0x26, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x45, 0x3d,
	0x1c, 0xa6, 0xea, 0x41, 0x8d, 0x2c, 0x0e, 0x82, 0x6b, 0x51, 0x32, 0xe1, 0xe2, 0x80, 0x89, 0x0a,
	0x09, 0x70, 0x31, 0x97, 0x24, 0xa6, 0x43, 0xad, 0x00, 0x31, 0x85, 0xc4, 0xb8, 0xd8, 0x8a, 0x4b,
	0x12, 0x4b, 0x4a, 0x41, 0x46, 0x83, 0x04, 0xa1, 0x3c, 0xa7, 0x78, 0x2e, 0xa9, 0xcc, 0x7c, 0x5c,
	0xd6, 0x04, 0x30, 0x46, 0x59, 0xa6, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea,
	0x43, 0x55, 0xc1, 0x69, 0xb0, 0xcf, 0xf5, 0xa1, 0x7a, 0xf4, 0xa1, 0x7a, 0xe2, 0xd3, 0xf3, 0xe3,
	0xc1, 0x12, 0x8b, 0x98, 0x98, 0xdd, 0x83, 0x1c, 0x93, 0xd8, 0xc0, 0x1c, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x60, 0x98, 0x74, 0x4c, 0x30, 0x01, 0x00, 0x00,
}
