// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entitlement.proto

package entitlement_go_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A note that indicates the entitlements on UEM
type Entitlement struct {
	Details              *Details `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entitlement) Reset()         { *m = Entitlement{} }
func (m *Entitlement) String() string { return proto.CompactTextString(m) }
func (*Entitlement) ProtoMessage()    {}
func (*Entitlement) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfb56f6f34698a02, []int{0}
}

func (m *Entitlement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entitlement.Unmarshal(m, b)
}
func (m *Entitlement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entitlement.Marshal(b, m, deterministic)
}
func (m *Entitlement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entitlement.Merge(m, src)
}
func (m *Entitlement) XXX_Size() int {
	return xxx_messageInfo_Entitlement.Size(m)
}
func (m *Entitlement) XXX_DiscardUnknown() {
	xxx_messageInfo_Entitlement.DiscardUnknown(m)
}

var xxx_messageInfo_Entitlement proto.InternalMessageInfo

func (m *Entitlement) GetDetails() *Details {
	if m != nil {
		return m.Details
	}
	return nil
}

// Details of a Citi occurrence.
type Details struct {
	// Required. SOEID
	Soeid string `protobuf:"bytes,1,opt,name=soeid,proto3" json:"soeid,omitempty"`
	// Required. APP CSI ID
	Csi string `protobuf:"bytes,2,opt,name=csi,proto3" json:"csi,omitempty"`
	// Required. Identifies a resource entitlement
	Entitlements         []*Entitlements `protobuf:"bytes,3,rep,name=entitlements,proto3" json:"entitlements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Details) Reset()         { *m = Details{} }
func (m *Details) String() string { return proto.CompactTextString(m) }
func (*Details) ProtoMessage()    {}
func (*Details) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfb56f6f34698a02, []int{1}
}

func (m *Details) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Details.Unmarshal(m, b)
}
func (m *Details) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Details.Marshal(b, m, deterministic)
}
func (m *Details) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Details.Merge(m, src)
}
func (m *Details) XXX_Size() int {
	return xxx_messageInfo_Details.Size(m)
}
func (m *Details) XXX_DiscardUnknown() {
	xxx_messageInfo_Details.DiscardUnknown(m)
}

var xxx_messageInfo_Details proto.InternalMessageInfo

func (m *Details) GetSoeid() string {
	if m != nil {
		return m.Soeid
	}
	return ""
}

func (m *Details) GetCsi() string {
	if m != nil {
		return m.Csi
	}
	return ""
}

func (m *Details) GetEntitlements() []*Entitlements {
	if m != nil {
		return m.Entitlements
	}
	return nil
}

// Details of a discovery occurrence.
type Entitlements struct {
	// Required. Resource name
	ResourceName string `protobuf:"bytes,1,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	// Required. Resource URI
	ResourceUri          string   `protobuf:"bytes,2,opt,name=resourceUri,proto3" json:"resourceUri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entitlements) Reset()         { *m = Entitlements{} }
func (m *Entitlements) String() string { return proto.CompactTextString(m) }
func (*Entitlements) ProtoMessage()    {}
func (*Entitlements) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfb56f6f34698a02, []int{2}
}

func (m *Entitlements) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entitlements.Unmarshal(m, b)
}
func (m *Entitlements) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entitlements.Marshal(b, m, deterministic)
}
func (m *Entitlements) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entitlements.Merge(m, src)
}
func (m *Entitlements) XXX_Size() int {
	return xxx_messageInfo_Entitlements.Size(m)
}
func (m *Entitlements) XXX_DiscardUnknown() {
	xxx_messageInfo_Entitlements.DiscardUnknown(m)
}

var xxx_messageInfo_Entitlements proto.InternalMessageInfo

func (m *Entitlements) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *Entitlements) GetResourceUri() string {
	if m != nil {
		return m.ResourceUri
	}
	return ""
}

func init() {
	proto.RegisterType((*Entitlement)(nil), "grafeas.v1beta1.entitlement.Entitlement")
	proto.RegisterType((*Details)(nil), "grafeas.v1beta1.entitlement.Details")
	proto.RegisterType((*Entitlements)(nil), "grafeas.v1beta1.entitlement.Entitlements")
}

func init() { proto.RegisterFile("entitlement.proto", fileDescriptor_bfb56f6f34698a02) }

var fileDescriptor_bfb56f6f34698a02 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0xcd, 0x2b, 0xc9,
	0x2c, 0xc9, 0x49, 0xcd, 0x4d, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x4e,
	0x2f, 0x4a, 0x4c, 0x4b, 0x4d, 0x2c, 0xd6, 0x2b, 0x33, 0x4c, 0x4a, 0x2d, 0x49, 0x34, 0xd4, 0x43,
	0x52, 0xa2, 0xe4, 0xcb, 0xc5, 0xed, 0x8a, 0xe0, 0x0a, 0xd9, 0x71, 0xb1, 0xa7, 0xa4, 0x96, 0x24,
	0x66, 0xe6, 0x14, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0xa9, 0xe8, 0xe1, 0xd1, 0xad, 0xe7,
	0x02, 0x51, 0x1b, 0x04, 0xd3, 0xa4, 0xd4, 0xc0, 0xc8, 0xc5, 0x0e, 0x15, 0x14, 0x12, 0xe1, 0x62,
	0x2d, 0xce, 0x4f, 0xcd, 0x4c, 0x01, 0x9b, 0xc4, 0x19, 0x04, 0xe1, 0x08, 0x09, 0x70, 0x31, 0x27,
	0x17, 0x67, 0x4a, 0x30, 0x81, 0xc5, 0x40, 0x4c, 0x21, 0x5f, 0x2e, 0x1e, 0x24, 0x33, 0x8b, 0x25,
	0x98, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x34, 0xf1, 0x5a, 0x8c, 0xe4, 0xe6, 0xe2, 0x20, 0x14, 0xed,
	0x4a, 0x21, 0x5c, 0x3c, 0xc8, 0xb2, 0x42, 0x4a, 0x5c, 0x3c, 0x45, 0xa9, 0xc5, 0xf9, 0xa5, 0x45,
	0xc9, 0xa9, 0x7e, 0x89, 0xb9, 0xa9, 0x50, 0xd7, 0xa0, 0x88, 0x09, 0x29, 0x70, 0x71, 0xc3, 0xf8,
	0xa1, 0x45, 0x30, 0xc7, 0x21, 0x0b, 0x39, 0xa5, 0x73, 0xc9, 0x65, 0xe6, 0xe3, 0x73, 0x52, 0x00,
	0x63, 0x94, 0x6d, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x3e, 0x54, 0x25,
	0x9c, 0x06, 0x47, 0x85, 0x3e, 0x54, 0x9f, 0x3e, 0x92, 0xbe, 0xf8, 0xf4, 0xfc, 0x78, 0xb0, 0xe4,
	0x22, 0x26, 0x66, 0xf7, 0x20, 0xc7, 0x24, 0x36, 0x30, 0xc7, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0x4b, 0xcd, 0x75, 0xed, 0xc9, 0x01, 0x00, 0x00,
}
